-- Stations of our own (issue #37).
--
-- Until now there was no station table at all: every "which stations are near me" question went
-- out to Transitous with the passenger's coordinates on it, and "is this stop a railway station"
-- was answered by sampling live departures. That is a lot of load on somebody else's volunteer
-- service, it is a coordinate leaving the phone, and it is all for data that changes a couple of
-- times a year.
--
-- So we hold the stations ourselves, with ids of our own. `stations.id` is the id the app sees
-- (as the string `vs:4711`), and it is permanent: an id is never reused, even after the station
-- it named is gone from the feed. The ids Transitous knows live in `station_sources`, one row per
-- feed that serves the station, and they are the only thing we ever put on the wire to MOTIS.
create table stations (
    id          integer primary key generated by default as identity,
    name        text             not null,   -- already through display_station_name()
    lat         double precision not null,
    lon         double precision not null,
    -- The docs/23 ladder: 3 long distance, 2 regional, 1 S-Bahn only. 0 never reaches this table.
    rank        smallint         not null,
    modes       text[]           not null default '{}',
    first_seen  timestamptz      not null default now(),
    last_seen   timestamptz      not null default now(),
    -- Gone from the feed. The row stays so the id stays spoken for, and so a ride that names it
    -- still reads back.
    retired_at  timestamptz
);

-- The nearby lookup is a scan over every live station, so the only thing an index has to do is
-- keep the retired ones out of it.
create index stations_live on stations (lat, lon) where retired_at is null;

-- The ids Transitous answers to. Several per station by design: Berlin's S-Bahn comes from the
-- VBB feed and its regional platforms from DELFI, and both are the same building.
create table station_sources (
    source_id  text        primary key,      -- 'de-DELFI_de:05315:11201', verbatim from stops.txt
    station_id integer     not null references stations(id) on delete cascade,
    feed       text        not null,         -- 'de-DELFI'
    -- The one `departures` and `plan` use. Exactly one per station.
    preferred  boolean     not null default false,
    last_seen  timestamptz not null default now()
);
create index station_sources_station on station_sources (station_id);
create unique index station_sources_one_preferred on station_sources (station_id) where preferred;

-- One row per import run, committed or refused, so that a bad import is a thing you can read
-- afterwards rather than a thing you notice in the app.
create table station_imports (
    id           integer primary key generated by default as identity,
    started_at   timestamptz not null default now(),
    finished_at  timestamptz,
    feed_version text,
    added        integer not null default 0,
    retired      integer not null default 0,
    moved        integer not null default 0,
    renamed      integer not null default 0,
    total        integer not null default 0,
    committed    boolean not null default false,
    note         text
);
